export const SERVICE_CATALOG = [
  {
    id: 'jules-cloud',
    title: 'Jules',
    subtitle: 'Cloud assistant',
    category: 'Coding Assistants',
    kind: 'cloud-api-key',
    provider: 'jules',
    icon: 'cloud',
    description: 'Connect Google Jules so cloud coding sessions can be launched and monitored here.',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Enter Jules API key' },
    ],
  },
  {
    id: 'cursor-cloud',
    title: 'Cursor',
    subtitle: 'Cloud assistant',
    category: 'Coding Assistants',
    kind: 'cloud-api-key',
    provider: 'cursor',
    icon: 'cloud_sync',
    description: 'Link the Cursor cloud API for hosted agents and repository access.',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Enter Cursor API key' },
    ],
  },
  {
    id: 'cursor-local',
    title: 'Cursor',
    subtitle: 'Local repositories',
    category: 'Coding Assistants',
    kind: 'local-path',
    provider: 'cursor',
    icon: 'laptop_windows',
    description: 'Add a local folder that contains Git repositories Cursor can work against.',
    fields: [
      { key: 'path', label: 'Repository Root', type: 'path', placeholder: 'Choose a folder with local Git repos' },
    ],
  },
  {
    id: 'codex-cloud',
    title: 'Codex',
    subtitle: 'OpenAI API',
    category: 'Coding Assistants',
    kind: 'cloud-api-key',
    provider: 'codex',
    icon: 'cloud',
    description: 'Connect the legacy Codex/OpenAI assistants API used by tracked Codex threads.',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Enter OpenAI API key' },
    ],
  },
  {
    id: 'codex-local',
    title: 'Codex',
    subtitle: 'Local repositories',
    category: 'Coding Assistants',
    kind: 'local-path',
    provider: 'codex',
    icon: 'terminal',
    description: 'Add a local repository root for Codex tasks and project discovery.',
    fields: [
      { key: 'path', label: 'Repository Root', type: 'path', placeholder: 'Choose a folder with local Git repos' },
    ],
  },
  {
    id: 'claude-cloud',
    title: 'Claude',
    subtitle: 'Anthropic API',
    category: 'Coding Assistants',
    kind: 'cloud-api-key',
    provider: 'claude',
    icon: 'cloud',
    description: 'Connect Anthropic so Claude conversations can run from the dashboard.',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Enter Anthropic API key' },
    ],
  },
  {
    id: 'claude-local',
    title: 'Claude Code',
    subtitle: 'Local CLI',
    category: 'Coding Assistants',
    kind: 'local-path',
    provider: 'claude',
    icon: 'memory',
    description: 'Verify Claude Code is installed and add a repository root for local sessions.',
    requiresInstall: true,
    fields: [
      { key: 'path', label: 'Repository Root', type: 'path', placeholder: 'Choose a folder with local Git repos' },
    ],
  },
  {
    id: 'gemini-local',
    title: 'Gemini CLI',
    subtitle: 'Local CLI',
    category: 'Coding Assistants',
    kind: 'local-path',
    provider: 'gemini',
    icon: 'computer',
    description: 'Verify Gemini CLI is available and add a repository root for local tasks.',
    requiresInstall: true,
    fields: [
      { key: 'path', label: 'Repository Root', type: 'path', placeholder: 'Choose a folder with local Git repos' },
    ],
  },
  {
    id: 'openrouter-cloud',
    title: 'OpenRouter',
    subtitle: 'Model provider',
    category: 'Model Providers',
    kind: 'cloud-api-key',
    provider: 'openrouter',
    icon: 'hub',
    description: 'Connect OpenRouter for orchestration model access.',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Enter OpenRouter API key' },
    ],
  },
  {
    id: 'openai-cloud',
    title: 'OpenAI',
    subtitle: 'Model provider',
    category: 'Model Providers',
    kind: 'cloud-api-key',
    provider: 'openai',
    icon: 'api',
    description: 'Connect OpenAI for orchestrator model access and API validation.',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Enter OpenAI API key' },
    ],
  },
  {
    id: 'gemini-api',
    title: 'Gemini API',
    subtitle: 'Model provider',
    category: 'Model Providers',
    kind: 'cloud-api-key',
    provider: 'gemini',
    icon: 'token',
    description: 'Connect the Gemini API for model access outside the local CLI.',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Enter Gemini API key' },
    ],
  },
  {
    id: 'github-cloud',
    title: 'GitHub',
    subtitle: 'Cloud integration',
    category: 'Integrations',
    kind: 'cloud-api-key',
    provider: 'github',
    icon: 'deployed_code',
    description: 'Connect GitHub so repositories, branches, and pull requests are available.',
    fields: [
      { key: 'apiKey', label: 'Personal Access Token', type: 'password', placeholder: 'Enter GitHub token with repo access' },
    ],
  },
  {
    id: 'github-local',
    title: 'GitHub Repositories',
    subtitle: 'Local paths',
    category: 'Integrations',
    kind: 'local-path',
    provider: 'github',
    icon: 'folder_code',
    description: 'Add local GitHub repository roots for local scans and repo creation flows.',
    fields: [
      { key: 'path', label: 'Repository Root', type: 'path', placeholder: 'Choose a folder with local Git repos' },
    ],
  },
  {
    id: 'jira-cloud',
    title: 'Jira',
    subtitle: 'Project integration',
    category: 'Integrations',
    kind: 'jira',
    provider: 'jira',
    icon: 'task_alt',
    description: 'Connect Jira with your site URL and token so backlog and sprint issues can be loaded.',
    fields: [
      { key: 'baseUrl', label: 'Jira Base URL', type: 'text', placeholder: 'https://your-domain.atlassian.net' },
      { key: 'apiKey', label: 'API Token', type: 'password', placeholder: 'Enter email:token or PAT' },
    ],
  },
  {
    id: 'cloudflare-sync',
    title: 'Cloudflare KV',
    subtitle: 'Sync integration',
    category: 'Integrations',
    kind: 'cloudflare',
    provider: 'cloudflare',
    icon: 'cloud_upload',
    description: 'Connect Cloudflare KV to sync service credentials and remote device state.',
    fields: [
      { key: 'accountId', label: 'Account ID', type: 'text', placeholder: 'Enter Cloudflare account ID' },
      { key: 'apiToken', label: 'API Token', type: 'password', placeholder: 'Enter Cloudflare API token' },
    ],
  },
];

export function getServiceDefinition(serviceId) {
  return SERVICE_CATALOG.find((service) => service.id === serviceId) || null;
}
